export default {
    REQUEST_STARTUPS: 'REQUEST_STARTUPS',
    RECEIVE_STARTUPS: 'RECEIVE_STARTUPS',
    SET_STARTUPS: 'SET_STARTUPS',

    REQUEST_OFFERS: 'REQUEST_OFFERS',
    RECEIVE_OFFERS: 'RECEIVE_OFFERS',
    SET_OFFERS: 'SET_OFFERS',
}